name = "casm"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
# go_version = "1.17"
# module_path = "github.com/wetware/lab"
exec_pkg = "."
go_proxy_mode = "remote"
go_proxy_url = "https://proxy.golang.org"

[builders."exec:go"]
enabled = true
# module_path = "github.com/wetware/lab"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "pex/convergence"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    convTickAmount = {type="int", default = 100}

[[testcases]]
name= "pex/resiliency"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    convTickAmount = {type="int", default = 100}
    churn = {type="float", default = 0.2}

[[testcases]]
name= "pex/fanout"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    convTickAmount = {type="int", default = 100}
    fanout = {type="int", default = 2}

[[testcases]]
name= "pex/resiliency"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    convTickAmount = {type="int", default = 100}
    churn = {type="float", default = 0.2}

[[testcases]]
name= "pex/strategy"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    convTickAmount = {type="int", default = 100}
    