name = "casm"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
# go_version = "1.17"
# module_path = "github.com/wetware/lab"
exec_pkg = "."
go_proxy_mode = "remote"
go_proxy_url = "https://proxy.golang.org"


[builders."exec:go"]
enabled = true
# module_path = "github.com/wetware/lab"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "pex"
instances = { min = 2, max = 64, default = 2 }

# Add more testcases here...
# [[testcases]]
# name = "another"
# instances = { min = 1, max = 1, default = 1 }
#   [testcase.params]
#   param1 = { type = "int", desc = "an integer", unit = "units", default = 3 }
