name = "casm"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.17"
# module_path = "github.com/wetware/lab"
exec_pkg = "."
go_proxy_mode = "remote"
go_proxy_url = "https://proxy.golang.org"

[builders."exec:go"]
enabled = true
# module_path = "github.com/wetware/lab"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name= "pex"
instances = { min = 2, max = 64, default = 2 }
    [testcases.params]
    tick = {type="int", default = 100}
    tickAmount = {type="int", default = 100}
    nodesAmount = {type="int", default = 100}
    c = {type="int", default = 30}
    s = {type="int", default = 10}
    p = {type="int", default = 5}
    d = {type="float", default = 0.005}
    partitionTick = {type="int", default = -1}
